### ISSUE TITLE
paper.md wording 

### ISSUE THREAD

**Issue by jaeyk** [MAnalytics/opitools#4]
I recommend tidying up some wordings in the `paper.md`. The following are examples I think that you can improve upon. 
 
"either in the field of natural language processing or computational linguistics" -> "natural language processing or computational linguistics" are not mutually exclusive categories. 

"including social sciences [@Somasundaran:2010; @Morency:2011; @Nikolovska:2020], market research [@Feldman:2011; @Otaibi:2018], and electoral politics [@Ansari:2020; @Connor:2010]" -> "electoral politics is a domain in social sciences, so listing these words as equal concepts would be not most appropriate."

**Comment by MAnalytics** [comment]
@jaeyk The wordings (as indicated) have now been tidied.

**Comment by cjbarrie** [comment]
Sorry to reopen, but didn't want to create multiple Issues. I have a few further language editing suggestions:

- "that does not only extracts inherent themes" should be "that not only extracts inherent themes'
- "holds prospect for wider applications" reads a bit oddly, how about just "has wider applications"
- then I'd delete "compared to the existing techniques, in the aforementioned application fields" as this is pretty much implicit anyway
- I would then also delete the lines "The demonstration of these examples can be found in the documentation of the package (please see the `README.md` file and the package `Vignette` for details). Lastly, it is argued that this contribution provides a framework by which some of the existing opinion mining tools [@Tai:2015; @Kiomourtzis:2014; @Wawer:2016; @Munson:2019] may be further advanced for wider research impacts." as I'm not sure these really add much without further comment on why the package advances these existing tools. Given this section is really supposed to be just a short Statement of Need, deleting these lines is appropriate.
- In the section "Key Functionalities" I would remove reference to function names (which may change) and instead just report the high-level functionality

**Comment by MAnalytics** [comment]
@cjbarrie Thank you very much for the excellent reviews. All the changes have been made accordingly.

MA.
